name: Maestro Tests

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  maestro:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Run Smoke Tests
        run: |
          maestro test test_add_contac.yaml