name: Maestro Tests

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  maestro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> "$GITHUB_PATH"

      - name: Check Maestro version
        run: maestro --version

      - name: Show project structure
        run: |
            pwd
            find . -maxdepth 4 -type f | sort

      - name: Run Smoke Tests
        run: |
          maestro test flows/test_add_contact.yaml